apiVersion: v1
kind: Pod
metadata:
  name: mysql-volume
  labels:
    app: bdd
spec:
  containers:
  - name: mysql
    image: mysql
    volumeMounts:
    - name: mysql-volume
      mountPath: /var/lib/mysql
    env:
    - name: MYSQL_DATABASE
      value: eazytraining
    - name: MYSQL_USER
      value: eazy
    - name: MYSQL_PASSWORD
      value: eazy
    - name: MYSQL_ROOT_PASSWORD
      value: password

  volumes:
  - name: mysql-volume
    hostPath:
      path: /data-volume
      type: DirectoryOrCreate
