apiVersion: v1
kind: Pod
metadata:
  name: mysql-pv
  labels:
    app: bdd
spec:
  containers:
  - name: mysql
    image: mysql
    volumeMounts:
    - name: mysql-data
      mountPath: /var/lib/mysql
    env:
    - name: MYSQL_DATABASE
      value: eazytraining
    - name: MYSQL_USER
      value: eazy
    - name: MYSQL_PASSWORD
      value: eazy
    - name: MYSQL_ROOT_PASSWORD
      value: password

  volumes:
  - name: mysql-data
    persistentVolumeClaim:
      claimName: pvc
