apiVersion: v1
kind: Pod
metadata:
  name: pod-red
  namespace: production
  labels:
    app: web
spec:
  containers:
  - name: simple-webapp
    image: mmumshad/simple-webapp-color
    env:
      - name: APP_COLOR
        value: red
    ports:
      - containerPort: 8080
